services:
  - type: web
    name: telegram-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8439119682:AAHV00Uk9LK90eoysUe7uKq3J56AcS3uPgQ
      - key: PROVIDER_TOKEN
        value: 390540012:LIVE:100092
      - key: YOUR_TELEGRAM_ID
        value: 6217476601
      - key: CHANNEL_ID
        value: -6217476601
      - key: PYTHON_VERSION
        value: 3.12.0
